### ISSUE TITLE
Subscription Support

### ISSUE THREAD

**Issue by nathan93** [samerton/Nameless-Tebex#12]
As the title says, right now the Tebex integration module does not support packages that are subscriptions, only on-off purchases. Would it be possible to have the Tebex integration have support for packages that can be purchased as subscriptions as well?

Thank you

**Comment by IkiaeM** [comment]
There is a problem with the Tebex integration, I'm talking to you because you publish the module. 

The problem is that when the article is a subscription the link to add it to the cart on tebex ends with /subscribe while a normal single article ends with /single.
And when it is a subscription actually it passes the link with /single and so tebex returns an error.
Would it be possible to fix this?

**Comment by samerton** [comment]
https://github.com/samerton/Nameless-Tebex/commit/5dbbf1f02538a33ce06a4190beeb4b323f13a7c4

**Comment by samerton** [comment]
Added in 1.3.0
